export { default as Dashboard } from './Dashboard'
export { default as AddEmployee } from './Employee/Add-Employee'
export { default as EditEmployee } from './Employee/Edit-Employee'
export { default as Employee } from './Employee/Employee'
export { default as NotFound } from './NotFound/NotFound'
export {default as Performance} from './Employee/Performance'
export {default as CompanyDetails} from './Company/companydetails'
export {default as Documents} from './Company/documents'
export {default as TimeOff} from './Time Tools/Timeoff'
export {default as TimeTracking} from './Time Tools/Timetracking'